### PR TITLE
Brandon

### PR DESCRIPTION
**Pull request by jeja**

### CODE REVIEW

**Comment by brakittl** [comment]
Awesome! Nice job I'll keep working on level creation

**Comment by brakittl** [comment]
Its going to be a pain, but you only merged my stuff with the master. Can
you merge your stuff in there so I can have your work on the turtle and
other stuff for level creation. Let me know if you need any help merging I
am free all day.

On Sat, Jan 23, 2016 at 5:08 PM, Brandon Kittle <brakittl@umich.edu> wrote:

> Awesome! Nice job I'll keep working on level creation
> On Jan 23, 2016 3:44 PM, "Julian Jackson" <notifications@github.com>
> wrote:
>
>> Merged #1 <https://github.com/jeja/Project_1_CrashBandicoot/pull/1>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jeja/Project_1_CrashBandicoot/pull/1#event-524000890>
>> .
>>
>


-- 

Brandon Kittle

University of Michigan, Class of 2016

College of Engineering

Computer Science Engineering

**Comment by jeja** [comment]
I think I just did it. Please let me know if there are issues! A lot of
problems I've been experiencing with is the meta folders

**Comment by jeja** [comment]
Nvm, it didn't work. Let me attach the files I've worked on. Also how are you merging with everything? I'm still getting error when I try.
[eecs494P.zip](https://github.com/jeja/Project_1_CrashBandicoot/files/103956/eecs494P.zip)

**Comment by brakittl** [comment]
Okay perfect. Ya I just started getting errors when pushing to the master.
I will compile all the code and try to over write the master so that it
should be fine. I don't know where these errors came from.

On Mon, Jan 25, 2016 at 3:56 PM, Julian Jackson <notifications@github.com>
wrote:

> Nvm, it didn't work. Let me attach the files I've worked on. Also how are
> you merging with everything? I'm still getting error when I try.
> eecs494P.zip
> <https://github.com/jeja/Project_1_CrashBandicoot/files/103956/eecs494P.zip>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeja/Project_1_CrashBandicoot/pull/1#issuecomment-174660277>
> .
>



-- 

Brandon Kittle

University of Michigan, Class of 2016

College of Engineering

Computer Science Engineering

**Pull request merged**
